#!/bin/bash

# Connect to the last used Wi-Fi network
is_connected=$(nmcli -t -f ACTIVE device wifi | grep yes)

if [ "$is_connected" != "yes" ]; then
    last_wifi=$(nmcli -t -f NAME connection show | sed -n '2p')
    nmcli connection up "$last_wifi"
fi
