#!/bin/bash

# Set the volume using playerctl
playerctl volume $1

# Check if the command was successful
if [ $? -eq 0 ]; then
    icon=$(playerctl -l | head -n 1 | cut -d '.' -f 1)
    volume=$(playerctl volume)
    volume_int=$(printf "%.0f" "$(echo "$volume * 100" | bc)")

    # Send a notification with the current volume
    notify-send --replace-id=4 --icon=$icon "Current volume is: $volume_int%"
fi
