#!/usr/bin/env python3
import subprocess

layout = subprocess.run("hyprctl getoption general:layout".split(), 
                        capture_output=True, text=True, check=True)

is_dwindle = "str: dwindle" in layout.stdout

if is_dwindle:
    subprocess.run("hyprctl keyword general:layout master".split())

else: 
    subprocess.run("hyprctl keyword general:layout dwindle".split())